import { Box, Grid, Heading, VStack, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Teamseas app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box textAlign="center" fontSize="xl">
        <Grid minH="100vh" p={3}>
          <VStack spacing={8}>
            <Image
              src="/logo.png"
              alt="Teamseas Logo"
              width={486}
              height={216}
            />
            <Heading as="h1" size="xl">
              {'Join the movement'.toUpperCase()}
            </Heading>
            <Text fontWeight="light">
              The team is growing everyday and scoring wins for the planet.
              Plant with us and track our progress
            </Text>
          </VStack>
        </Grid>
      </Box>
    </main>
  );
};

export default Home;
